import fs from "fs";
import csv from "csv-parser";

// 🔹 Path to your dhan instrument CSV
const CSV_FILE_PATH = "../../api-scrip-master.csv";

// 🔹 Client symbols
const CLIENT_SYMBOLS = new Set([
  "BANKNIFTY","FINNIFTY","MIDCPNIFTY","NIFTY","NIFTYNXT50",
  "360ONE","ABB","ABCAPITAL","ADANIENSOL","ADANIENT","ADANIGREEN","ADANIPORTS",
  "ALKEM","AMBER","AMBUJACEM","ANGELONE","APLAPOLLO","APOLLOHOSP","ASHOKLEY",
  "ASIANPAINT","ASTRAL","AUBANK","AUROPHARMA","AXISBANK","BAJAJ-AUTO",
  "BAJAJFINSV","BAJAJHLDNG","BAJFINANCE","BANDHANBNK","BANKBARODA",
  "BANKINDIA","BDL","BEL","BHARATFORG","BHARTIARTL","BHEL","BIOCON",
  "BLUESTARCO","BOSCHLTD","BPCL","BRITANNIA","BSE","CAMS","CANBK","CDSL",
  "CGPOWER","CHOLAFIN","CIPLA","COALINDIA","COFORGE","COLPAL","CONCOR",
  "CROMPTON","CUMMINSIND","DABUR","DALBHARAT","DELHIVERY","DIVISLAB",
  "DIXON","DLF","DMART","DRREDDY","EICHERMOT","ETERNAL","EXIDEIND",
  "FEDERALBNK","FORTIS","GAIL","GLENMARK","GMRAIRPORT","GODREJCP",
  "GODREJPROP","GRASIM","HAL","HAVELLS","HCLTECH","HDFCAMC","HDFCBANK",
  "HDFCLIFE","HEROMOTOCO","HINDALCO","HINDPETRO","HINDUNILVR","HINDZINC",
  "HUDCO","ICICIBANK","ICICIGI","ICICIPRULI","IDEA","IDFCFIRSTB","IEX",
  "INDHOTEL","INDIANB","INDIGO","INDUSINDBK","INDUSTOWER","INFY",
  "INOXWIND","IOC","IREDA","IRFC","ITC","JINDALSTEL","JIOFIN",
  "JSWENERGY","JSWSTEEL","JUBLFOOD","KALYANKJIL","KAYNES","KEI",
  "KFINTECH","KOTAKBANK","KPITTECH","LAURUSLABS","LICHSGFIN","LICI",
  "LODHA","LT","LTF","LTM","LUPIN","M&M","MANAPPURAM","MANKIND",
  "MARICO","MARUTI","MAXHEALTH","MAZDOCK","MCX","MFSL","MOTHERSON",
  "MPHASIS","MUTHOOTFIN","NATIONALUM","NAUKRI","NBCC","NESTLEIND",
  "NHPC","NMDC","NTPC","NUVAMA","NYKAA","OBEROIRLTY","OFSS","OIL",
  "ONGC","PAGEIND","PATANJALI","PAYTM","PERSISTENT","PETRONET","PFC",
  "PGEL","PHOENIXLTD","PIDILITIND","PIIND","PNB","PNBHOUSING",
  "POLICYBZR","POLYCAB","POWERGRID","POWERINDIA","PPLPHARMA",
  "PREMIERENE","PRESTIGE","RBLBANK","RECLTD","RELIANCE","RVNL",
  "SAIL","SAMMAANCAP","SBICARD","SBILIFE","SBIN","SHREECEM",
  "SHRIRAMFIN","SIEMENS","SOLARINDS","SONACOMS","SRF","SUNPHARMA",
  "SUPREMEIND","SUZLON","SWIGGY","SYNGENE","TATACONSUM","TATAELXSI",
  "TATAPOWER","TATASTEEL","TATATECH","TCS","TECHM","TIINDIA",
  "TITAN","TMPV","TORNTPHARM","TORNTPOWER","TRENT","TVSMOTOR",
  "ULTRACEMCO","UNIONBANK","UNITDSPR","UNOMINDA","UPL","VBL",
  "VEDL","VOLTAS","WAAREEENER","WIPRO","YESBANK","ZYDUSLIFE"
]);

const results = [];

fs.createReadStream(CSV_FILE_PATH)
  .pipe(csv())
  .on("data", (row) => {
    const tradingSymbol = row["SEM_TRADING_SYMBOL"]?.trim();

    if (CLIENT_SYMBOLS.has(tradingSymbol)) {
      results.push({
        symbol: tradingSymbol,
        security_id: row["SEM_SMST_SECURITY_ID"],
        exchange_id: row["SEM_EXM_EXCH_ID"]
      });
    }
  })
  .on("end", () => {
    console.log("✅ Matched Symbols:\n");
    console.table(results);

    // Optional: Save to JSON
    fs.writeFileSync("mappedSymbols.json", JSON.stringify(results, null, 2));
    console.log("\n📁 Saved to mappedSymbols.json");
  })
  .on("error", (err) => {
    console.error("❌ Error reading CSV:", err);
  });